# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

# GET Customers
@PageNumber = 1
@PageSize = 10
GET {{Web_HostAddress}}/api/Customers?ListId=1&PageNumber={{PageNumber}}&PageSize={{PageSize}}

###

# POST Customers
POST {{Web_HostAddress}}/api/Customers
Content-Type: application/json

// CreateCustomerCommand
{
    "firstName": "John",
    "lastName": "Doe",
    "dateOfBirth": "1990-01-01T00:00:00",
    "phoneNumber": 09124798930,
    "email": "johndoe@example.com",
    "bankAccountNumber": "12345678910"
}


###

#PUT Customers UpdateItemDetails
PUT {{Web_HostAddress}}/api/Customers/UpdateItemDetails?Id=1
Content-Type: application/json

// UpdateCustomerDetailCommand
{
    "firstName": "John",
    "lastName": "Doe",
    "dateOfBirth": "1990-01-01T00:00:00",
    "phoneNumber": 09124798930,
    "email": "johndoe@example.com",
    "bankAccountNumber": "12345678910"
}

###

# PUT Customers
PUT {{Web_HostAddress}}/api/Customers/1
Content-Type: application/json

// UpdateCustomerCommand
{
    "firstName": "John",
    "lastName": "Doe",
    "dateOfBirth": "1990-01-01T00:00:00",
    "phoneNumber": 09124798930,
    "email": "johndoe@example.com",
    "bankAccountNumber": "12345678910"
}

###

# DELETE Customer
DELETE {{Web_HostAddress}}/api/Customers/1

###